[[redirects]]
from = "https://melodie-et-cie.netlify.app/*"
to = "https://melodie-et-cie.sandbox.leopeyronnet.fr/:splat"
status = 301
force = true

[build]
  command = "npm run build"
  publish = "_site"