backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "formations"
    label: "Formation"
    folder: "src/services/formation"
    create: true
    identifier_field: name
    summary: "{{emoji}} {{name}}"
    slug: "{{name | slugify}}"
    editor:
      preview: false
    format: "json"
    extension: "json"
    fields:
      - { label: "Emoji", name: "emoji", widget: "string" }
      - { label: "Nom de la formation", name: "name", widget: "text" }
      - { label: "Description courte", name: "shortDescription", widget: "text" }
      - { label: "Description longue", name: "longDescription", widget: "text" }
      - { label: "Professeurs", name: "teachers", widget: "list", summary: "{{fields.item}}" }
      - { label: "Styles", name: "styles", widget: "list", summary: "{{fields.item}}" }
      - { label: "Nom de la section (hash)", name: "hash", widget: "string" }

  - name: "upcoming_events"
    label: "Événements à venir"
    folder: "src/services/evenements/upcoming"
    create: true
    identifier_field: title
    summary: "{{emoji}} {{title}}"
    slug: "{{title | slugify}}-{{date | slugify}}"
    editor:
      preview: false
    format: "json"
    extension: "json"
    fields:
      - { label: "Emoji", name: "emoji", widget: "string", default: "🎵" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Lieu", name: "location", widget: "string" }
      - { label: "Lien (optionnel)", name: "href", widget: "string", required: false }
      - { label: "Illustration", name: "image", widget: "image"}

  - name: "programmable_events"
    label: "Événements programmables"
    folder: "src/services/evenements/programmable"
    create: true
    identifier_field: title
    summary: "{{emoji}} {{title}}"
    slug: "{{title | slugify}}"
    editor:
      preview: false
    format: "json"
    extension: "json"
    fields:
      - { label: "Emoji", name: "emoji", widget: "string", default: "🎵" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Durée", name: "duration", widget: "string" }
      - { label: "Prix", name: "price", widget: "string" }
      - { label: "Description", name: "descr", widget: "text" }
      - { label: "Contenu du bouton", name: "cta_label", widget: "string" }
      - { label: "Lien du bouton", name: "cta_link", widget: "string" }